ADF-3636 - Salesforce: Report on client agents + versions
AbleTech/addressfinder-salesforce pull request #9
Opened 2024-09-02 23:43 UTC by smingins

- added `ca` option to source code and examples

2024-09-02 23:53 UTC, erikfercak requested changes

2024-09-02 23:53 UTC, erikfercak commented on source/addressfinder_salesforce_au.js
> +            clientAgentVersion = 'Salesforce/1.0.2',
It would be nice if the version string did not need to be repeated twice in the same file. Could you rework the code so that you could end up with
```javascript
clientAgentVersion = `Salesforce/${this.version}`,
```
instead? Applies to the nz page as well.

2024-09-03 00:08 UTC, smingins commented on source/addressfinder_salesforce_au.js
> +            clientAgentVersion = 'Salesforce/1.0.2',
So like:

```
   *
   * VERSION SalesforcePlugin.VERSION
   *
   * Copyright (c) 2016 Abletech
   */
  (function (d, w) {
    const VERSION = '1.0.2';
```

And 

```
        clientAgentVersion = `Salesforce/${VERSION}`,
```
As that `1.0.2` is in the comments ... I am not sure of another way of indicating it in the comment?

2024-09-03 00:33 UTC, erikfercak commented on source/addressfinder_salesforce_au.js
> +            clientAgentVersion = 'Salesforce/1.0.2',
There is no actual need to have the version specified in the comments too, having it as a constant is perfectly fine.

2024-09-03 02:41 UTC, erikfercak approved these changes
👍

2024-09-03 03:10 UTC, merged